# Generated by Django 5.2.7 on 2025-11-13 07:38

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='question_mark.jpg', upload_to=products.models.upload_to_app),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='question_mark.jpg', upload_to=products.models.upload_to_app),
        ),
    ]
