# Generated by Django 5.2.7 on 2025-11-16 15:32

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='core/static/core/img/question_mark.jpg', upload_to=products.models.upload_to_app),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='core/static/core/img/question_mark.jpg', upload_to=products.models.upload_to_app),
        ),
    ]
